version: '3'
services:
  database-mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: bhtcnpm
      MYSQL_DATABASE: rainy_words_adventure
    expose:
      - 3306

  be:
    build:
      context: ../rainy-words-adventure-be
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3306
      - DB_HOST=database-mysql
      - URL_REACT=http://localhost
    ports:
      - 8080:8080
    depends_on:
      - database-mysql

  fe-nginx:
    build:
      context: ../rainy-words-adventure-fe
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - be
