export const fakeStudent = [
    {
        studentID: 1,
        grade: 5,
        birthday: '2009-01-01',
        useName: 'student1',
        passWord: '123456',
        schoolID: 1,
    },
    {
        studentID: 2,
        grade: 6,
        birthday: '2010-02-02',
        useName: 'student2',
        passWord: 'abcdef',
        schoolID: 2,
    },
    {
        studentID: 3,
        grade: 7,
        birthday: '2011-03-03',
        useName: 'student3',
        passWord: 'qwerty',
        schoolID: 3,
    },
    {
        studentID: 4,
        grade: 8,
        birthday: '2012-04-04',
        useName: 'student4',
        passWord: 'password4',
        schoolID: 4,
    },
    {
        studentID: 5,
        grade: 9,
        birthday: '2013-05-05',
        useName: 'student5',
        passWord: 'password5',
        schoolID: 5,
    },
    // ... repeat the pattern for students 6 to 49
    {
        studentID: 10,
        grade: 10,
        birthday: '2016-01-05',
        useName: 'student10',
        passWord: 'mno345',
        schoolID: 15,
    },
    {
        studentID: 11,
        grade: 10,
        birthday: '2016-01-06',
        useName: 'student11',
        passWord: 'pqr678',
        schoolID: 16,
    },
    {
        studentID: 12,
        grade: 10,
        birthday: '2016-01-07',
        useName: 'student12',
        passWord: 'stu901',
        schoolID: 17,
    },
   
    {
        studentID: 49,
        grade: 10,
        birthday: '2016-01-23',
        useName: 'student49',
        passWord: 'password49',
        schoolID: 22,
    },
    {
        studentID: 50,
        grade: 10,
        birthday: '2016-01-24',
        useName: 'student50',
        passWord: 'xyz123',
        schoolID: 23,
    }
]